# Generated by Django 3.2.9 on 2022-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.IntegerField(choices=[(1, 'Phone'), (2, 'Facebook'), (3, 'Email')], default=1, verbose_name='Тип'),
        ),
    ]
